# Generated by Django 5.1.3 on 2024-12-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('niceness_coefficient', models.FloatField()),
                ('gift', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SantasList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naughty_list', models.ManyToManyField(blank=True, related_name='naughty_kids', to='santa_list.kid')),
                ('nice_list', models.ManyToManyField(blank=True, related_name='nice_kids', to='santa_list.kid')),
            ],
        ),
    ]
