# Generated by Django 5.1.3 on 2024-12-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='santaslist',
            name='naughty_list',
            field=models.ManyToManyField(blank=True, related_name='naughty_list', to='santa_list.kid'),
        ),
        migrations.AlterField(
            model_name='santaslist',
            name='nice_list',
            field=models.ManyToManyField(blank=True, related_name='nice_list', to='santa_list.kid'),
        ),
    ]
