# Generated by Django 5.1.3 on 2024-12-27 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('santa_list', '0002_alter_santaslist_naughty_list_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('kid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='santa_list.kid')),
            ],
        ),
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toy_type', models.CharField(max_length=255)),
                ('kid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='santa_list.kid')),
            ],
        ),
    ]
